### ISSUE TITLE
Regexes for system words

### ISSUE THREAD

**Issue by kuzyn** [solyarisoftware/ChatScript.vim#1]
Good stuff @solyaris! Glad that you finally got that ball rolling. You're giving me reasons reconsider vim for ChatScript ;P

Feel free to copy regexes from my `tmlanguage` files if you want. System functions, system variables and constants are pretty much exhaustive up until CS version 7.2

https://github.com/kuzyn/chatscript-tmlanguage/blob/master/Chatscript.JSON-tmLanguage

Cheers

**Comment by solyarisoftware** [comment]
Hi Samuel,

BTW, I used with success your sublimetext editor plugin (and I updated this page on the ChatScript github home): https://github.com/bwilcox-1234/ChatScript/tree/master/Third%20Party%20Tools#sublime-text-editor

In facts, initially I used your regexes :) but afterward,  I temporarily decided to avoid to deepen on detail of each system function

Also I  didn't used "standard" vim association between a color and the symbol typology.
For example, typical assignment  is to associate to all kind of variables, a specific color for variables.
I opted instead to give different color to different type of variable (`$va`l != `$$var` != `$_var` != `%var`) , etc.

But thank you  for your note and I'll eventually stole again from your tmlanguage code :-)

Last but not least, 
I'm not a vim regex expert (vim regex dialect is also a bit peculiar) and my syntax highlight code for vim is now really rough and draft!  I'll do better asap and of course any help is welcome.
cheers
giorgio
